CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY, login TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL, admin BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 expires_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS events (
 id BIGSERIAL PRIMARY KEY, title TEXT NOT NULL,
 starts_at TIMESTAMPTZ NOT NULL, rows INTEGER NOT NULL CHECK(rows BETWEEN 1 AND 20),
 cols INTEGER NOT NULL CHECK(cols BETWEEN 1 AND 20)
);
CREATE TABLE IF NOT EXISTS bookings (
 id BIGSERIAL PRIMARY KEY, event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 seat INTEGER NOT NULL CHECK(seat > 0), UNIQUE(event_id, seat)
);
CREATE TABLE IF NOT EXISTS app_migrations (version INTEGER PRIMARY KEY);
INSERT INTO events(title, starts_at, rows, cols)
SELECT 'Отчётный концерт фортепианного отделения', NOW() + INTERVAL '30 days', 10, 10
WHERE NOT EXISTS (SELECT 1 FROM app_migrations WHERE version=1);
INSERT INTO app_migrations(version) VALUES(1) ON CONFLICT DO NOTHING;
