apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: school
resources:
  - app.yaml
  - database.yaml
images:
  - name: school-backend
    newName: ghcr.io/waontest999/music-school-lab3-backend
    newTag: latest
  - name: school-frontend
    newName: ghcr.io/waontest999/music-school-lab3-frontend
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "false"